backend:
  name: github
  repo: morrislaptop/looped
  commit_messages:
    create: "docs: create {{slug}}"
    update: "docs: update {{slug}}"
    delete: "docs: delete {{slug}}"
    uploadMedia: "docs: upload media {{path}}"
    deleteMedia: "docs: delete media {{path}}"

media_folder: "packages/docs/.vuepress/public/images"
public_folder: "packages/docs/.vuepress/dist/"

collections:
  - name: "doc"
    label: "Doc"
    folder: "packages/docs"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
